repos:
  - repo: /home/admin/pre-commit/flake8
    rev: 4.0.0
    hooks:
      - id: flake8
        exclude: |
            (?x)^(
                examples/|
                cookbook/|
                client_tools/|
                src/twinkle_client|
            )$
  - repo: /home/admin/pre-commit/isort
    rev: 4.3.21
    hooks:
      - id: isort
        exclude: |
            (?x)^(
                examples/|
                cookbook/|
                client_tools/|
                src/twinkle_client|
            )$
  - repo: /home/admin/pre-commit/mirrors-yapf
    rev: v0.30.0
    hooks:
      - id: yapf
        exclude: |
            (?x)^(
                examples/|
                cookbook/|
                client_tools/|
                src/twinkle_client|
            )$
  - repo: /home/admin/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: trailing-whitespace
      - id: check-yaml
      - id: end-of-file-fixer
      - id: requirements-txt-fixer
      - id: double-quote-string-fixer
      - id: check-merge-conflict
      - id: fix-encoding-pragma
        args: [ "--remove" ]
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
