repos:
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.3.0
    hooks:
      - id: flake8
        exclude: |
            (?x)^(
                examples/|
                cookbook/|
                client_tools/|
                src/twinkle_client|
                
            )$
  - repo: https://github.com/PyCQA/isort.git
    rev: 7.0.0
    hooks:
      - id: isort
        exclude: |
            (?x)^(
                examples/|
                cookbook/|
                client_tools/|
                src/twinkle_client|
            )$
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        exclude: |
            (?x)^(
                examples/|
                cookbook/|
                client_tools/|
                src/twinkle_client|
            )$
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v6.0.0
    hooks:
